INSERT INTO movies (name, genre, release) VALUES ('All Quiet on the Western Front', 'War', 2022)
INSERT INTO movies (name, genre, release) VALUES ('The Social Network', 'Drama', 2010)
INSERT INTO movies (name, genre, release) VALUES ('Wall-E', 'Adventure', 2008)
INSERT INTO movies (name, genre, release) VALUES ('The Dark Knight', 'Action', 2008)
INSERT INTO movies (name, genre, release) VALUES ('Parasite', 'Thriller', 2019)
INSERT INTO movies (name, genre, release) VALUES ('12 Years a Slave', 'Drama', 2019)
INSERT INTO movies (name, genre, release) VALUES ('Saving Private Ryan', 'Drama', 1998)
